version: '3.4'

volumes:
  postgres-bridge-volume:

services:
  postgres-bridge:
    image: postgres:15.1-alpine
    restart: on-failure
    ports:
      - '5439:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: badpassword
      POSTGRES_DB: bridge
    volumes:
      - postgres-bridge-volume:/var/lib/postgresql/data
